name: Francisco Fern치ndez Casta침o
url: http://fcofdez.github.io
description: Francisco Fern치ndez Casta침o blog.

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
